import dotenv from 'dotenv';

// Load .env and override any pre-existing env so local .env is authoritative in dev
dotenv.config({ override: true });

const {
  PORT,
  DEV,
  USE_MOCK_SERVICES,
  ADMIN_TOKEN,
  TWILIO_ACCOUNT_SID,
  TWILIO_AUTH_TOKEN,
  TWILIO_WHATSAPP_FROM,
  TWILIO_WEBHOOK_URL,
  TWILIO_CONTENT_SID_CONFIRMATION,
  TWILIO_CONTENT_SID_FIELD_SELECTION,
  TWILIO_CONTENT_SID_COMPANY_SELECTION,
  WHATSAPP_ALLOWED_NUMBERS,
  OPENAI_API_KEY,
  OPENAI_MODEL,
  SPREADSHEET_ID,
  DRIVE_UPLOAD_FOLDER_ID,
  COMPANY_ATOMO_NAME,
  COMPANY_ATOMO_SPREADSHEET_ID,
  COMPANY_ATOMO_DRIVE_FOLDER_ID,
  COMPANY_APRILIS_NAME,
  COMPANY_APRILIS_SPREADSHEET_ID,
  COMPANY_APRILIS_DRIVE_FOLDER_ID,
  COMPANY_MASIVA_NAME,
  COMPANY_MASIVA_SPREADSHEET_ID,
  COMPANY_MASIVA_DRIVE_FOLDER_ID,
} = process.env;

const parseAllowlist = (value?: string) =>
  (value || '')
    .split(',')
    .map((entry) => entry.trim())
    .filter(Boolean);

export const env = {
  PORT: PORT || '3000',
  DEV: DEV === 'true' || false,
  USE_MOCK_SERVICES: USE_MOCK_SERVICES === 'true' || false,
  ADMIN_TOKEN: ADMIN_TOKEN || '',
  TWILIO_ACCOUNT_SID: TWILIO_ACCOUNT_SID || '',
  TWILIO_AUTH_TOKEN: TWILIO_AUTH_TOKEN || '',
  TWILIO_WHATSAPP_FROM: TWILIO_WHATSAPP_FROM || '',
  TWILIO_WEBHOOK_URL: TWILIO_WEBHOOK_URL || '',
  TWILIO_CONTENT_SID_CONFIRMATION: TWILIO_CONTENT_SID_CONFIRMATION || '',
  TWILIO_CONTENT_SID_FIELD_SELECTION: TWILIO_CONTENT_SID_FIELD_SELECTION || '',
  TWILIO_CONTENT_SID_COMPANY_SELECTION: TWILIO_CONTENT_SID_COMPANY_SELECTION || '',
  WHATSAPP_ALLOWED_NUMBERS: parseAllowlist(WHATSAPP_ALLOWED_NUMBERS),
  OPENAI_API_KEY: OPENAI_API_KEY || '',
  OPENAI_MODEL: OPENAI_MODEL || 'gpt-4o-mini',
  SPREADSHEET_ID: SPREADSHEET_ID || '',
  DRIVE_UPLOAD_FOLDER_ID: DRIVE_UPLOAD_FOLDER_ID || '',
  COMPANY_ATOMO_NAME: COMPANY_ATOMO_NAME || 'Átomo Consulting SAC',
  COMPANY_ATOMO_SPREADSHEET_ID: COMPANY_ATOMO_SPREADSHEET_ID || '',
  COMPANY_ATOMO_DRIVE_FOLDER_ID: COMPANY_ATOMO_DRIVE_FOLDER_ID || '',
  COMPANY_APRILIS_NAME: COMPANY_APRILIS_NAME || 'Aprilis EIRL',
  COMPANY_APRILIS_SPREADSHEET_ID: COMPANY_APRILIS_SPREADSHEET_ID || '',
  COMPANY_APRILIS_DRIVE_FOLDER_ID: COMPANY_APRILIS_DRIVE_FOLDER_ID || '',
  COMPANY_MASIVA_NAME: COMPANY_MASIVA_NAME || 'Masiva Estrategias SAC',
  COMPANY_MASIVA_SPREADSHEET_ID: COMPANY_MASIVA_SPREADSHEET_ID || '',
  COMPANY_MASIVA_DRIVE_FOLDER_ID: COMPANY_MASIVA_DRIVE_FOLDER_ID || '',
};

export default env;
