import dotenv from 'dotenv';

// Load .env and override any pre-existing env so local .env is authoritative in dev
dotenv.config({ override: true });

const {
  PORT,
  DEV,
  USE_MOCK_SERVICES,
  ADMIN_TOKEN,
  TWILIO_ACCOUNT_SID,
  TWILIO_AUTH_TOKEN,
  TWILIO_WHATSAPP_FROM,
  TWILIO_WEBHOOK_URL,
  TWILIO_CONTENT_SID_CONFIRMATION,
  TWILIO_CONTENT_SID_FIELD_SELECTION,
  OPENAI_API_KEY,
  OPENAI_MODEL,
  SPREADSHEET_ID,
  DRIVE_UPLOAD_FOLDER_ID,
} = process.env;

export const env = {
  PORT: PORT || '3000',
  DEV: DEV === 'true' || false,
  USE_MOCK_SERVICES: USE_MOCK_SERVICES === 'true' || false,
  ADMIN_TOKEN: ADMIN_TOKEN || '',
  TWILIO_ACCOUNT_SID: TWILIO_ACCOUNT_SID || '',
  TWILIO_AUTH_TOKEN: TWILIO_AUTH_TOKEN || '',
  TWILIO_WHATSAPP_FROM: TWILIO_WHATSAPP_FROM || '',
  TWILIO_WEBHOOK_URL: TWILIO_WEBHOOK_URL || '',
  TWILIO_CONTENT_SID_CONFIRMATION: TWILIO_CONTENT_SID_CONFIRMATION || '',
  TWILIO_CONTENT_SID_FIELD_SELECTION: TWILIO_CONTENT_SID_FIELD_SELECTION || '',
  OPENAI_API_KEY: OPENAI_API_KEY || '',
  OPENAI_MODEL: OPENAI_MODEL || 'gpt-4o-mini',
  SPREADSHEET_ID: SPREADSHEET_ID || '',
  DRIVE_UPLOAD_FOLDER_ID: DRIVE_UPLOAD_FOLDER_ID || '',
};

export default env;
